### ISSUE TITLE
Druid options for Dismount?

### ISSUE THREAD

**Issue by BradCOnGitHub** [xod-wow/LiteMount#12]
I'm looking for a way to make Dismount not send me back to the previous druid form. Cat form is sort of a "hobo travel form" since it's faster than walking so it gets used all the time when indoors or in combat. Once I'm out of this and can get into travel form I don't want to return to cat form when I dismount. The reason this is bad is that going into cat form again causes a full GCD but a simple canceling of travel form only puts travel form on cool down. Surprise attacks from the air go wrong, especially in PvP.

**Comment by BradCOnGitHub** [comment]
I did more reading and found CancelForm. Should really put that on the Advanced Options page

I ended up replacing the default Dismount with this:

CancelForm
IF [mounted]
  Dismount
END


The IF is needed because it doesn't do as the Mount Selection Order page says. Without it if I use a real mount then it somehow cancels the mount then puts me into travel form in the same action, which is generally not a bad thing, just weird.

**Comment by mbattersby** [comment]
CancelForm doesn't do anything as of LiteMount 9.0.1, so including it doesn't do anything. That's why it isn't on the advanced options page. What you have written is equivalent to:

Dismount [mounted]

What you probably want is this:

Script [form] /cancelform

before the Dismount action.

Alternatively, you can set Travel Form to priority 0 to disable all the automated processing, then put your own activate and cancel actions in the Unvailable macro.

**Comment by BradCOnGitHub** [comment]
You're right. No idea why I thought I was seeing CancelForm do something. I should probably sleep more...

Just the changing to Dismount [mounted] seems to get what I need (that syntax is much better too). My guess is it goes to the end and when it tries to mount again it finds travel form and toggles it. What I don't understand is why I return to cat form with the default and not with the [mounted].

**Comment by mbattersby** [comment]
I think your guess is spot on. A happy accident. :) You might want to keep the Script line in mind in case you ever learn Mount Form from the vendor.

Happy adventuring, X.
