### ISSUE TITLE
Detect which mount is active in Advanced Options?

### ISSUE THREAD

**Issue by kps1ny** [xod-wow/LiteMount#137]
Hi, and thanks for the LiteMount add-on.

In the Advanced Options area, is it possible to detect which mount has just been mounted and is now active? I'd like to use if/else to then summon certain companion pets, depending on the mount that was just chosen randomly from a certain custom set of the mounts I have.

My thinking is that it would be something like this:

IF [mounted:Dark Iron Core Hound]
Use Core Hound Pup
END

As input, that appears to do nothing; same if enclosing the mount name with quotation marks; same if using just mount. The macro guide you provide seems to offer this type of possibility for pets, but not for mounts.

is there any other way to detect one's active mount, by name or by code, and then act on it?

-Ken

**Comment by mbattersby** [comment]
I think, although I haven't tested it, that the [aura] condition would detect this since mounts put a buff on you.

E.g.,

`IF [aura:Dark Iron Core Hound]`

It won't work in one button press though, because (a) LiteMount will stop processing after it calls the mount (there's no way around this WoW won't let you cast two things in one go in an addon only sometimes with macros), and (b) even if it could you wouldn't actually be mounted yet when LiteMount tried to run the line.

The [mounted] and [pet] conditions are just copied from what Blizzard does, though it would make sense for [mounted] to take arguments simiilarly I suppose.

There used to be an addon to summon matching companion pets, MountMiniMe. You might check if it's still being maintained or still works.

**Comment by kps1ny** [comment]
OK, thanks for that. The MountMiniMe add-on has not been updated since Oct. 16, 2020, so alas, it's not going to work.

**Comment by mbattersby** [comment]
I apologise, I guess, but summoning pets is not really something I feel belongs in LiteMount but in another "Summon pet under conditions" addon. Unfortunately I don't know if any still exist that are being maintained, but I'm only one person I can't solve every problem. :(

**Comment by kps1ny** [comment]
No worries, that's totally understandable. It seemed worth asking, though, just in case it could be done. No need to apologize. Carry on, enjoy coding what you want :-)
