### ISSUE TITLE
Passenger Mounts when Grouped

### ISSUE THREAD

**Issue by imrayzor** [xod-wow/LiteMount#17]
Option: Select only passenger mounts in party/raid

When in a party having the option to only select passenger mounts would be useful. (i.e. Sandstone Drake, Traveler's Tundra Mammoth, or the passenger travel forms,, etc.) Currently I have limited LM to only select passenger mounts all the time but think it would be nice to enable the selection of random mounts when not in a group and passenger mounts when in a group if desired.

**Comment by mbattersby** [comment]
This is possible already using the Advanced Options:

https://github.com/xod-wow/LiteMount/wiki/Passenger-Mounts-When-Grouped

I'm not going to add a specific on/off check box for it, otherwise I'd have 200 check boxes by now. I hope to someday add more UI panels to allow some simpler "advanced" option settings, but it won't be any time soon with the SL release.

**Comment by imrayzor** [comment]
The advanced option makes perfect sense. I didn't realize that was possible. Thank you.

**Comment by mbattersby** [comment]
You're welcome!

Happy adventuring, X.
