### ISSUE TITLE
Toy usage broken

### ISSUE THREAD

**Issue by LootFever** [xod-wow/LiteMount#205]
Since the 10.2.6 patch the usage of toys via LiteMount is broken.
Instead of the toy being used (may it be 1 or 2 clicks), it just shows the message `You can't mount here.`

And its not just Hearthstones. I tested it with the Fae Harp, same problem.

### Advanced Options > Keybinding:

`Use 184489`

### Debug:
```
LiteMount: [4] PreClick handler (inputButton=LeftButton, isDown=false) 
LiteMount:   Dispatching rule Use 184489 
LiteMount:   * trying item Fae Harp 
LiteMount:   * setting action to can't mount now 
LiteMount: [4] PreClick fail time 0.52 
LiteMount: [4] PostClick handler (inputButton=LeftButton, isDown=false)
```

Tested with the latest 10.2.6, 10.2.5 and 10.2.0 version of the addon.
Same result every time.

Not sure if something in LiteMount changed or if it's a Blizzard "Issue".
Just wanted to check-in before I report it as a possible bug to Blizzard.

**Comment by mbattersby** [comment]
There's no changes to LiteMount, but Blizzard seem to have broken a lot of things in this patch since it got no testing. If I bind 'StartAttack' to a key and push it I get a LUA error entirely within the base Blizzard code.

I'm sure this will be something simple but I don't have a lot of time to debug at the moment. The limited time nature and the mount rewards from the plunder event mean I'm going to have to spend my free wow time grinding it even though I don't enjoy it.

**Comment by mbattersby** [comment]
Please try 10.2.6-2.

**Comment by LootFever** [comment]
From what I can see it works now just like it used too.
Thanks for the quick fix. 😉
