### ISSUE TITLE
Druid: summon mount if standing still option

### ISSUE THREAD

**Issue by KestrelWild** [xod-wow/LiteMount#22]
Would it be possible to add the ability for druids to cast from the regular mount list if standing still, but to use travel form if you hit the keybinding while moving? I've used other addons in the past that had this and loved it.

**Comment by mbattersby** [comment]
I think this should be possible without too much effort. I expect the option to be "Only use instant-cast mounts while moving." or some wording like that, since it will apply to more than just Travel Form.

What's going to take a while is getting the wording right then getting it translated into all the wow languages.

**Comment by mbattersby** [comment]
A testing version of this is in LiteMount 9.0.18, but not enabled in the UI. If you want to test it out for me, you can do:

```/run LiteMount.LM.Options.db.profile.instantOnlyMoving = true```

and to turn it off again use false instead of true.

I don't have time to test it out at the moment, and I don't have a druid leveled to 60 yet.

**Comment by KestrelWild** [comment]
it works! yay!

**Comment by mbattersby** [comment]
Wonderful, thanks for testing it out. I'm not sure when I'll have time to put the options checkbox in. I'm not very good at the UI programming so it takes me a long time.

**Comment by mbattersby** [comment]
Faster than I expected, the UI for this is in LiteMount 9.0.19.

Happy adventuring, X.

**Comment by KestrelWild** [comment]
awesome - thank you!
