### ISSUE TITLE
Default to Aerial Unit R-21/X in Mechagon

### ISSUE THREAD

**Issue by CTumminaro** [xod-wow/LiteMount#41]
More of a feature request than a bug. However, I would expect to Smart Mount on the Aerial Unit R-21/X in Mechagon as opposed to a random flying mount due to being targeted for dismount when flying anything else.

**Comment by mbattersby** [comment]
I didn't know that mount had that benefit. It seems like Rustbolt Resistor maybe also has the same effect, are you able to check?

I was going to put this in as a default rule with the new Rules system (currently in the beta releases, coming soon) but now it's two mounts it would require a group to be made.

It's a good idea. I will think about how to do it.

**Comment by mbattersby** [comment]
I think, with the new Rules feature available in 9.1.2 and on, I am going to move away from making default rules like this and let people put them in themselves. Once people have edited the rules themselves, the default rules are kind of irrelevant so adding new ones won't do anything.

if you have a strong opinion about this one way or the other, I am open to suggestions.

**Comment by CTumminaro** [comment]
Sorry missed this notification. It is only the flying mount that has the benefit. The other Aerial Units only target flying mounts. I will however look into the new Rules feature in 9.1.2, they sound great! Keep up the great work!

**Comment by mbattersby** [comment]
No problem, a lot of the comments here are me talking to myself about what I might need to do anyway.

I've confirmed (by going to Mechagon and afk flying there for 10 minutes) that Rustbolt Resistor definitely has the same effect of making you not targeted by the HK-8 Aerial Oppression Unit. I sadly don't have Aerial Unit R-21/X so I could not compare the two but I assume it's the same effect.

I'm still thinking about this, I'm going to leave the issue open for a while so I come back and look at it again later. Hopefully the rules will allow you to solve the problem for yourself as well.

**Comment by mbattersby** [comment]
I don't think there's any real way to do this now. Because of the way AceDB stores options (and in general the way that ordered lists work), even if I add this to the default rules everyone with any rules of their own will never see it.

It's a shame. I have enjoyed giving people cool defaults over the years. But short of AceDB being updated to support a better way of doing defaults, which is so unlikely as to be impossible, I'd have to write my own AceDB. And I just think it would take time away from better things I could do.

I feel kind of sad about this now. Oh well.
