### ISSUE TITLE
Automatic zone based filtering

### ISSUE THREAD

**Issue by jukefr** [xod-wow/LiteMount#45]
This is a suggestion, feel free to do what you want of it, the same can arguably already be achieved with some manual tweaking in the add-on.

The idea would be to automatically pick mounts based on a few criteria, such as :
- zone (select zone specific mount if you have it, ex: mawsworn soulhunter in the maw)
- expansion (select expansion specific mounts in expansion zones, ex: ashes in outland)
- instances (mounts that drop in the current instance)
- racial (only mounts tied to the current race)

These could be toggles and also have a priority/fallback concept when the mounts are not available (prioritize zone mount, then expansion mount, then default behavior of add-on etc.)

There's probably a few more criteria you could come up with. These are mainly focused on role-play and immersion, I guess.
I have never coded a proper add-on, so I have little to no clue of how complex such a feature would be to implement, nor would I have the time to do it myself honestly, hence the "suggestion".

edit: added instance criteria idea
edit: added racial

**Comment by mbattersby** [comment]
HI there, thanks for your suggestion. This is something I'll have to think about for a bit, there's a lot to unpack.

Apart from the issue of trying to decide what would be the right things to do, there just isn't a lot of good information about mounts in the game. What zone a mount is from, what instance it drops in, and what race a mount is for are not things you can query. Because I only have a limited amount of time for LiteMount and it tends to come in bursts, things where I have to maintain a lot of data about mounts by hand are often impractical. Pretty much the things you see in the mount filter drop-down menu are what's available in-game – except Family which I am maintaining myself.

I sometimes wonder if a better idea would be for people to share their profiles, since you can import and export them.

Sorry this is a bit unfocused. TL;DR, I appreciate the suggestion and it's given me some things to think about. Feel free to expand on it or put in more suggestions whenever you want.

**Comment by jukefr** [comment]
Hey,
Completely understand the lack of time to implement this, it's already very nice of you to make this codebase open sourced and interact with the people who use it !
If I have some spare time during the weekend, I'll look into "data brokers" and what can be achieved with data already available via other add-ons. I know that "Rarity" contains quite an extensive base of data that could **potentially** be used to achieve this.
Just a thought.

**Comment by mbattersby** [comment]
I think, on the whole, I am just not smart enough to come up with rules people would want and not find annoying. I suspect everyone would want something different in any case.

I have opened #55 to remind me to think about whether there would be a way for people to share rules with each other, similar to how weakauras can be shared. That sounds very hard and I don't suspect it will be any time soon.

Thanks for the suggestion, but I think LiteMount will remain more of a "let you do it however you want" addon rather than one that tries to have a lot of complicated defaults.

Happy adventuring, X.
