### ISSUE TITLE
Shaman ghost wolf

### ISSUE THREAD

**Issue by mmmunafo** [xod-wow/LiteMount#7]
When inside, shaman can use the ghost wolf, but he cannot convert back / dismount, because 'You can't mount here".

I see it's marked in Changes, as a "feature". I'm not sure it's one, also because one still get the annoying error message, and the old behavior was rather practical, I suppose, to fast switching form while running inside.

**Comment by mbattersby** [comment]
There's no advantage to cancelling Ghost Wolf form though. Any action you take will automatically switch you back, and otherwise you're just making yourself move slower.

The advantage (and the reason for the change), is that now you can mount up from Ghost Wolf without having to activate LiteMount twice. This seems to be how most people want it to work.

You can, if you want to, use the Unavailable Macro to cancel Ghost Wolf. That will restore to you the behaviour you're after:

/cancelform [form]

**Comment by mbattersby** [comment]
I have added an FAQ about this:

https://github.com/xod-wow/LiteMount/wiki/Ghost-Wolf-(Shamans)

**Comment by mmmunafo** [comment]
Thank you. 
I understand it's a reasonable behavior, and might be a little more efficient to be able to mount directly from ghost wolf form.
Previous behavior felt natural and worked out-of-the-box. Now shamans will have to explicitly change the addon configuration to get that behavior back or just to remove the error message when indoor. The FAQ will definitely help.

**Comment by mbattersby** [comment]
I'll keep an eye on this, and I do appreciate your feedback. The dozens of requests for this over the years still have me convinced the new behaviour is how most people want it to work, but if I'm wrong I'll change my mind and put it back.

Happy adventuring, X.
