### ISSUE TITLE
Underwater mounts while wanting to leave a body of water

### ISSUE THREAD

**Issue by abjugard** [xod-wow/LiteMount#9]
The way the addon currently works is, as you know, to mount an underwater mount if in a body of water, unless the character is at the surface where the normal rules apply.

This is pretty great most of the time, but every now and again I find myself juuuuust shy of being "at the surface", and the chosen mount will be an underwater mount, which can't fly, dismounts, drops my character back in the body of water, and forces me to mount up again after having verified my character is indeed at the surface this time.

I don't know what API:s are available for addons, but would it be possible to determine how deep in a body of water my character is, and only select an underwater mount if my character is more than 1 meter or so deep in the body of water?

**Comment by mbattersby** [comment]
Sadly, there are no APIs for anything like that. If there were, LiteMount would definitely use them.

The only available check is IsSubmerged() which returns whether you are swimming or standing on the bottom of water. There is not even an API to determine if you are floating on the top, which is why you have to jump out and activate LiteMount within 1 second to use a flying mount.

**Comment by abjugard** [comment]
Ah, that's a shame.
